### ISSUE TITLE
d3flux does not display in jupyterlab

### ISSUE THREAD

**Issue by djinnome** [pstjohn/d3flux#10]
Hi Peter,

We love using d3flux, but it only works in jupyter notebook, not jupyter lab. Is there any debug info I can provide to help you figure out what the issue is?

Sincerely,

Jeremy

**Comment by pstjohn** [comment]
I had to make a couple changes to the code, so you'll need to reinstall from pip.

Also, you need to put this cell in the jupyterlab environment before you run the d3flux command:

```python
from IPython.display import HTML

def add_require_js():
  display(HTML('<script src="/static/components/requirejs/require.js"></script>'
               '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">'))

get_ipython().events.register('pre_run_cell', add_require_js)
```

svg export seems to be broken on jupyterlab, not sure why. It's just a hacky implementation of svg-crowbar2 though.

**Comment by djinnome** [comment]
Thanks, Peter. That worked!

**Comment by pstjohn** [comment]
the old solution doesn't look like its working anymore, but this seems to work:
```
%%HTML
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
```
