### ISSUE TITLE
flux map not shown anymore

### ISSUE THREAD

**Issue by petzel96** [pstjohn/d3flux#12]
Hi Peter,

I am a big fan of d3flux and am currently writing part of my thesis with it. 
I encountered an issue today. All the flux_map commands don't show any network anymore.

Everything worked fine last week but now I am not able to see anything. I tried different browser, reinstalled and don't know what to do. I don't get any error messages. Everything executes fine.

Thanks,
Tim

**Comment by cnoecker** [comment]
I am having the same problem, using jupyter core version 4.6.3 on Safari and Chrome. flux_map runs and displays the 3 buttons (Save JSON/Show Reaction Nodes/Download SVG), but the visualization is not generated. I tested it with the example notebooks and the code in the documentation as well, all showed the same behavior.

**Comment by pstjohn** [comment]
I just encountered this as well; it's because they moved the cola.v3.min.js script from its previous location. I'll try to find that script again... the most recent cola.min.js didn't seem to work the same way

**Comment by pstjohn** [comment]
hopefully this is fixed in 0.2.7

**Comment by cnoecker** [comment]
Yes, seems to be working now. Thanks!
