### ISSUE TITLE
More complicated example

### ISSUE THREAD

**Issue by pstjohn** [pstjohn/d3flux#6]
I should add the code for one of the more complicated maps to show off some of the less documented features. Background guides, cofactors, label alignment, etc.

**Comment by migp11** [comment]
It is possible to draw just a subset of given reactions, for instance just reaction belonging to a single subsystem such as glycolysis? Thanks for the package very nice and useful.
Best,
Miguel

**Comment by pstjohn** [comment]
Yeah, its possible. Just set all the other reactions to have 

```python
reaction.notes['map_info']['hidden'] = True
```

I added a larger example in [`d3flux/examples/asuc`](https://github.com/pstjohn/d3flux/tree/master/d3flux/examples/asuc) in case that helps
