### ISSUE TITLE
"Untangled" pathway representations?

### ISSUE THREAD

**Issue by man-shu** [pstjohn/d3flux#8]
Hey again,
I must say, d3flux works like a charm. But when the number of nodes is large, the representation that it returns is very "tangled" and messy, the user needs to manually arrange the nodes so that the network makes sense. So, is there any way we can solve this problem?

**Comment by pstjohn** [comment]
Yeah its tough. One way is to add metabolites as 'cofactors' to reactions, especially if for the highly connected ones.

I.e, 
model.reactions.GLCpts.notes['map_info']['cofactors'] = {'pyr_c': {}, 'pep_c': {}}

for a PEP-PYR import

**Comment by man-shu** [comment]
Tried this, but the reactions arrows didn't show up. So, how do I define the stoichiometric coefficients for the metabolites (added as cofactors) in the reactions?

**Comment by man-shu** [comment]
This worked. Thanks!!
